package com.promotion.pojo;

import java.util.Date;

public class SmzdmJr {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_smzdm_jr.id
     *
     * @mbg.generated Tue Apr 10 13:23:11 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_smzdm_jr.title
     *
     * @mbg.generated Tue Apr 10 13:23:11 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_smzdm_jr.url
     *
     * @mbg.generated Tue Apr 10 13:23:11 CST 2018
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_smzdm_jr.descripe
     *
     * @mbg.generated Tue Apr 10 13:23:11 CST 2018
     */
    private String descripe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_smzdm_jr.descripeMD5
     *
     * @mbg.generated Tue Apr 10 13:23:11 CST 2018
     */
    private String descripemd5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_smzdm_jr.status
     *
     * @mbg.generated Tue Apr 10 13:23:11 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_smzdm_jr.create_time
     *
     * @mbg.generated Tue Apr 10 13:23:11 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_smzdm_jr.update_time
     *
     * @mbg.generated Tue Apr 10 13:23:11 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_smzdm_jr.id
     *
     * @return the value of t_smzdm_jr.id
     *
     * @mbg.generated Tue Apr 10 13:23:11 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_smzdm_jr.id
     *
     * @param id the value for t_smzdm_jr.id
     *
     * @mbg.generated Tue Apr 10 13:23:11 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_smzdm_jr.title
     *
     * @return the value of t_smzdm_jr.title
     *
     * @mbg.generated Tue Apr 10 13:23:11 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_smzdm_jr.title
     *
     * @param title the value for t_smzdm_jr.title
     *
     * @mbg.generated Tue Apr 10 13:23:11 CST 2018
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_smzdm_jr.url
     *
     * @return the value of t_smzdm_jr.url
     *
     * @mbg.generated Tue Apr 10 13:23:11 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_smzdm_jr.url
     *
     * @param url the value for t_smzdm_jr.url
     *
     * @mbg.generated Tue Apr 10 13:23:11 CST 2018
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_smzdm_jr.descripe
     *
     * @return the value of t_smzdm_jr.descripe
     *
     * @mbg.generated Tue Apr 10 13:23:11 CST 2018
     */
    public String getDescripe() {
        return descripe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_smzdm_jr.descripe
     *
     * @param descripe the value for t_smzdm_jr.descripe
     *
     * @mbg.generated Tue Apr 10 13:23:11 CST 2018
     */
    public void setDescripe(String descripe) {
        this.descripe = descripe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_smzdm_jr.descripeMD5
     *
     * @return the value of t_smzdm_jr.descripeMD5
     *
     * @mbg.generated Tue Apr 10 13:23:11 CST 2018
     */
    public String getDescripemd5() {
        return descripemd5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_smzdm_jr.descripeMD5
     *
     * @param descripemd5 the value for t_smzdm_jr.descripeMD5
     *
     * @mbg.generated Tue Apr 10 13:23:11 CST 2018
     */
    public void setDescripemd5(String descripemd5) {
        this.descripemd5 = descripemd5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_smzdm_jr.status
     *
     * @return the value of t_smzdm_jr.status
     *
     * @mbg.generated Tue Apr 10 13:23:11 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_smzdm_jr.status
     *
     * @param status the value for t_smzdm_jr.status
     *
     * @mbg.generated Tue Apr 10 13:23:11 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_smzdm_jr.create_time
     *
     * @return the value of t_smzdm_jr.create_time
     *
     * @mbg.generated Tue Apr 10 13:23:11 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_smzdm_jr.create_time
     *
     * @param createTime the value for t_smzdm_jr.create_time
     *
     * @mbg.generated Tue Apr 10 13:23:11 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_smzdm_jr.update_time
     *
     * @return the value of t_smzdm_jr.update_time
     *
     * @mbg.generated Tue Apr 10 13:23:11 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_smzdm_jr.update_time
     *
     * @param updateTime the value for t_smzdm_jr.update_time
     *
     * @mbg.generated Tue Apr 10 13:23:11 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}