package com.promotion.dao;

import com.promotion.pojo.SmzdmJr;
import com.promotion.pojo.SmzdmJrExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmzdmJrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_smzdm_jr
     *
     * @mbg.generated Tue Apr 10 13:23:11 CST 2018
     */
    long countByExample(SmzdmJrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_smzdm_jr
     *
     * @mbg.generated Tue Apr 10 13:23:11 CST 2018
     */
    int deleteByExample(SmzdmJrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_smzdm_jr
     *
     * @mbg.generated Tue Apr 10 13:23:11 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_smzdm_jr
     *
     * @mbg.generated Tue Apr 10 13:23:11 CST 2018
     */
    int insert(SmzdmJr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_smzdm_jr
     *
     * @mbg.generated Tue Apr 10 13:23:11 CST 2018
     */
    int insertSelective(SmzdmJr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_smzdm_jr
     *
     * @mbg.generated Tue Apr 10 13:23:11 CST 2018
     */
    List<SmzdmJr> selectByExample(SmzdmJrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_smzdm_jr
     *
     * @mbg.generated Tue Apr 10 13:23:11 CST 2018
     */
    SmzdmJr selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_smzdm_jr
     *
     * @mbg.generated Tue Apr 10 13:23:11 CST 2018
     */
    int updateByExampleSelective(@Param("record") SmzdmJr record, @Param("example") SmzdmJrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_smzdm_jr
     *
     * @mbg.generated Tue Apr 10 13:23:11 CST 2018
     */
    int updateByExample(@Param("record") SmzdmJr record, @Param("example") SmzdmJrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_smzdm_jr
     *
     * @mbg.generated Tue Apr 10 13:23:11 CST 2018
     */
    int updateByPrimaryKeySelective(SmzdmJr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_smzdm_jr
     *
     * @mbg.generated Tue Apr 10 13:23:11 CST 2018
     */
    int updateByPrimaryKey(SmzdmJr record);
}